#!/bin/bash
set -euo pipefail
. "$(cd "$(dirname "$0")" && pwd)/common.sh"
. "$LAUNCHER_DIR/target.env"

check_architecture
mkdir -p "$STATE_DIR" "$CACHE_DIR" "$LOG_DIR" "$UV_DIR" "$BROWSER_DIR"
chmod 700 "$STATE_DIR" "$CACHE_DIR" "$LOG_DIR"
printf 'Setting up Dola Gateway for macOS (%s)...\n' "$EXPECTED_ARCH"

if [[ ! -x "$UV_BIN" ]]; then
    download_dir="$(/usr/bin/mktemp -d "$CACHE_DIR/uv-download.XXXXXX")"
    trap '/bin/rm -rf "$download_dir"' EXIT
    archive="$download_dir/uv.tar.gz"
    printf 'Downloading verified uv %s...\n' "$UV_VERSION"
    /usr/bin/curl --fail --location --proto '=https' --tlsv1.2 "$UV_URL" -o "$archive"
    actual_sha="$(/usr/bin/shasum -a 256 "$archive" | /usr/bin/awk '{print $1}')"
    if [[ "$actual_sha" != "$UV_SHA256" ]]; then
        printf 'uv checksum mismatch. Expected %s, received %s.\n' "$UV_SHA256" "$actual_sha" >&2
        exit 1
    fi
    /usr/bin/tar -xzf "$archive" -C "$download_dir"
    /bin/cp "$download_dir/uv-$UV_TARGET/uv" "$UV_BIN"
    /bin/chmod 755 "$UV_BIN"
    /bin/rm -rf "$download_dir"
    trap - EXIT
fi

export UV_PYTHON_INSTALL_DIR="$CACHE_DIR/python"
export UV_CACHE_DIR="$CACHE_DIR/uv-cache"
export UV_MANAGED_PYTHON=1
"$UV_BIN" python install 3.13
if [[ ! -x "$VENV_PYTHON" ]]; then
    "$UV_BIN" venv --managed-python --python 3.13 "$VENV_DIR"
fi

printf 'Installing application dependencies...\n'
"$UV_BIN" pip install --python "$VENV_PYTHON" --requirement "$APP_DIR/requirements-macos.txt"
printf 'Installing Patchright Chromium...\n'
"$VENV_PYTHON" -m patchright install chromium

if [[ ! -f "$ENV_FILE" ]]; then
    client_key="sk-$(/usr/bin/openssl rand -hex 24)"
    admin_key="admin-$(/usr/bin/openssl rand -hex 24)"
    /bin/cat > "$ENV_FILE" <<EOF
# Generated by macOS setup. Keep this file private.
DOLA_HOST=127.0.0.1
DOLA_PORT=8000
DOLA_PUBLIC_BASE=http://127.0.0.1:8000
DOLA_API_KEYS=$client_key
DOLA_ADMIN_KEY=$admin_key
DOLA_PROXY=
DOLA_BROWSER_EXECUTABLE=
DOLA_HEADLESS=1
DOLA_IMAGE_HEADLESS=1
DOLA_MAX_CONCURRENCY=1
DOLA_MAX_PENDING_TASKS=25
DOLA_ACCOUNTS_CONFIG=accounts.local.json
DOLA_ACCOUNTS_DIR=accounts
DOLA_DB_PATH=tasks.db
DOLA_POOL_DB_PATH=pool_usage.db
DOLA_DOWNLOAD_DIR=downloads
EOF
    chmod 600 "$ENV_FILE"
    printf '\nGenerated private credentials:\n'
    printf '  Admin key:  %s\n' "$admin_key"
    printf '  Client key: %s\n' "$client_key"
    printf 'They are stored in %s\n' "$ENV_FILE"
fi

if [[ ! -f "$STATE_DIR/accounts.local.json" ]]; then
    printf '{"accounts":[]}\n' > "$STATE_DIR/accounts.local.json"
    chmod 600 "$STATE_DIR/accounts.local.json"
fi
mkdir -p "$STATE_DIR/accounts" "$STATE_DIR/downloads"

cd "$APP_DIR"
"$VENV_PYTHON" -c "import fastapi, aiohttp, pydantic, patchright, PIL, cv2; import config; print('Application import check passed')"
"$VENV_PYTHON" "$LAUNCHER_DIR/browser_check.py"

printf '\nSetup completed. The local dashboard will open now.\n'
"$LAUNCHER_DIR/run.sh"
