. (Join-Path $PSScriptRoot "common.ps1")

try {
    Write-Host "Setting up Dola Gateway for Windows..." -ForegroundColor Cyan
    New-Item -ItemType Directory -Force -Path $script:StateDir, $script:RuntimeDir, $script:BrowserDir, $script:LogDir | Out-Null
    Set-GatewayEnvironment

    $pythonCandidates = @()
    $launcher = Get-Command py.exe -ErrorAction SilentlyContinue
    if ($launcher) {
        foreach ($selector in @("-3.14", "-3.13", "-3.12", "-3.11", "-3")) {
            $pythonCandidates += [pscustomobject]@{
                Executable = $launcher.Source
                PrefixArgs = @($selector)
                Label = "py.exe $selector"
            }
        }
    }

    foreach ($commandName in @("python.exe", "python3.exe")) {
        $command = Get-Command $commandName -ErrorAction SilentlyContinue
        if ($command) {
            $pythonCandidates += [pscustomobject]@{
                Executable = $command.Source
                PrefixArgs = @()
                Label = $command.Source
            }
        }
    }

    $standardPatterns = @(
        (Join-Path $env:LOCALAPPDATA "Programs\Python\Python*\python.exe"),
        (Join-Path $env:ProgramFiles "Python*\python.exe")
    )
    foreach ($pattern in $standardPatterns) {
        foreach ($file in Get-ChildItem -Path $pattern -File -ErrorAction SilentlyContinue) {
            $pythonCandidates += [pscustomobject]@{
                Executable = $file.FullName
                PrefixArgs = @()
                Label = $file.FullName
            }
        }
    }

    $pythonExecutable = $null
    $pythonPrefixArgs = @()
    $versionText = $null
    $architecture = $null
    $detected = @()
    foreach ($candidate in $pythonCandidates) {
        $prefix = @($candidate.PrefixArgs)
        $probe = & $candidate.Executable @prefix -c "import platform,sys; print('.'.join(map(str, sys.version_info[:3])) + '|' + platform.architecture()[0])" 2>$null
        if ($LASTEXITCODE -ne 0 -or -not $probe) { continue }
        $parts = (($probe -join "").Trim()).Split("|")
        if ($parts.Count -ne 2) { continue }
        $candidateVersion = $parts[0]
        $candidateArchitecture = $parts[1]
        $detected += "$($candidate.Label) -> Python $candidateVersion ($candidateArchitecture)"
        if ([version]$candidateVersion -ge [version]"3.11" -and $candidateArchitecture -eq "64bit") {
            $pythonExecutable = $candidate.Executable
            $pythonPrefixArgs = $prefix
            $versionText = $candidateVersion
            $architecture = $candidateArchitecture
            break
        }
    }
    if (-not $pythonExecutable) {
        $details = if ($detected.Count) { " Detected: " + ($detected -join "; ") } else { " No working Python command was detected." }
        throw "No suitable 64-bit Python 3.11+ runtime was found.$details Install Python from https://www.python.org/downloads/windows/ and run setup again."
    }
    Write-Host "Using Python $versionText ($architecture)"

    if (-not (Test-Path $script:VenvPython)) {
        Write-Host "Creating the private Python environment..."
        & $pythonExecutable @pythonPrefixArgs -m venv $script:VenvDir
        if ($LASTEXITCODE -ne 0) { throw "Failed to create the Python environment." }
    }

    Write-Host "Installing application dependencies..."
    & $script:VenvPython -m ensurepip --upgrade
    if ($LASTEXITCODE -ne 0) { throw "Failed to initialize pip." }
    & $script:VenvPython -m pip install --disable-pip-version-check --upgrade pip
    if ($LASTEXITCODE -ne 0) { throw "Failed to update pip." }
    & $script:VenvPython -m pip install --disable-pip-version-check --requirement (Join-Path $script:AppDir "requirements-windows.txt")
    if ($LASTEXITCODE -ne 0) { throw "Failed to install application dependencies." }

    Write-Host "Installing Patchright Chromium (this is a large download)..."
    & $script:VenvPython -m patchright install chromium
    if ($LASTEXITCODE -ne 0) { throw "Failed to install Patchright Chromium." }

    if (-not (Test-Path $script:EnvFile)) {
        $clientKey = "sk-" + (New-RandomSecret 24)
        $adminKey = "admin-" + (New-RandomSecret 24)
        @"
# Generated by the Windows setup. Keep this file private.
DOLA_HOST=127.0.0.1
DOLA_PORT=8000
DOLA_PUBLIC_BASE=http://127.0.0.1:8000
DOLA_API_KEYS=$clientKey
DOLA_ADMIN_KEY=$adminKey
DOLA_PROXY=
DOLA_BROWSER_EXECUTABLE=
DOLA_HEADLESS=1
DOLA_IMAGE_HEADLESS=1
DOLA_MAX_CONCURRENCY=1
DOLA_MAX_PENDING_TASKS=25
DOLA_ACCOUNTS_CONFIG=accounts.local.json
DOLA_ACCOUNTS_DIR=accounts
DOLA_DB_PATH=tasks.db
DOLA_POOL_DB_PATH=pool_usage.db
DOLA_DOWNLOAD_DIR=downloads
"@ | Set-Content -LiteralPath $script:EnvFile -Encoding UTF8
        Write-Host "Generated new private credentials:" -ForegroundColor Yellow
        Write-Host "  Admin key:  $adminKey"
        Write-Host "  Client key: $clientKey"
        Write-Host "Save them in a password manager and do not send them to anyone."
    } else {
        Write-Host "Keeping the existing private configuration at $script:EnvFile"
    }

    $accountsFile = Join-Path $script:StateDir "accounts.local.json"
    if (-not (Test-Path $accountsFile)) {
        $utf8NoBom = New-Object System.Text.UTF8Encoding -ArgumentList $false
        [IO.File]::WriteAllText($accountsFile, '{"accounts":[]}', $utf8NoBom)
    }
    New-Item -ItemType Directory -Force -Path (Join-Path $script:StateDir "accounts"), (Join-Path $script:StateDir "downloads") | Out-Null

    Push-Location $script:AppDir
    try {
        & $script:VenvPython -c "import fastapi, aiohttp, pydantic, patchright, PIL, cv2; import config; print('Application import check passed')"
        if ($LASTEXITCODE -ne 0) { throw "The application import check failed." }
        & $script:VenvPython (Join-Path $PSScriptRoot "browser_check.py")
        if ($LASTEXITCODE -ne 0) { throw "Patchright Chromium could not pass its offline launch check." }
    } finally {
        Pop-Location
    }

    Write-Host ""
    Write-Host "Setup completed." -ForegroundColor Green
    Write-Host "Private data: $script:StateDir"
    Write-Host "Double-click run.cmd to start the gateway."
    exit 0
} catch {
    Write-Error $_
    exit 1
}
